run_mode: cross_validation
model: refusion_cascade_rescale
target: 'Cardiomegaly'
num_gpus: 1
additional_tags: ['12_5_threshold_ablation_gmeans', 'refusion']

conv: ['resnet', 8]
dropout: 0.1

num_classes: 1
learning_rate: 0.0001
batch_size: 64

patient_labels_path: '/home/xlx9645/chexpert/train.csv'
patient_info_path: '/home/xlx9645/chexpert/CHEXPERT DEMO.xlsx'
image_root: '/home/xlx9645/chexpert/'
sensitive_attributes: ['PRIMARY_RACE', 'GENDER', 'AGE_AT_CXR']
use_attrs: {
    'PRIMARY_RACE': ['White', 'Non-White'],
    'GENDER': ['Female', 'Male'],
    'AGE_AT_CXR': ['<60', '>=60'],
}

d_model_cv_root: '/home/xlx9645/FCRO-Fair-Classification-Orthogonal-Representation-main/results/${target}_all_cv_w_cond/'

model_save_root: 'checkpoints/refusion_${target}_cross_validation/'
data_cache_path: 'data_cache/${target}_all_cv_9_27.pkl'

max_epochs: 10
mean_std_dim: 256
cv_fold_idx: 0
cv_fold_total: 5
sa_encoder: simple
num_cascade_blocks: 2
# norm_rescale: True
adv_alpha: 0.1

use_group_specific_threshold: True
print_calibration: False
plot_subgroup_performance: True

test_model_root: '/home/xlx9645/fairness-refusion/checkpoints/refusion_Cardiomegaly_cross_validation/98bfb1e333ca4e77b4da95a7065d13b0/'
plot_roc_path: 'figs/'
test_refit_threshold: True