name: fairread
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - bleach=4.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.2
  - fontconfig=2.14.1
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.2
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.10
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libglib=2.78.4
  - libgomp=14.1.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.1
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mistune=2.0.4
  - mysql=5.7.24
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - openssl=3.3.1
  - overrides=7.4.0
  - packaging=24.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.21
  - pygments=2.18.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.4
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.5.1
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=69.5.1
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.1
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - art==6.3
      - attrs==23.2.0
      - captum==0.7.0
      - certifi==2024.7.4
      - click==8.1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==2.20.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - easydict==1.13
      - einops==0.8.0
      - et-xmlfile==1.1.0
      - filelock==3.15.4
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - ftfy==6.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glances==4.1.2
      - h5py==3.11.0
      - huggingface-hub==0.29.3
      - hydra-core==1.3.2
      - imageio==2.36.0
      - imbalanced-learn==0.12.4
      - ipdb==0.13.13
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - lightning==2.3.3
      - lightning-utilities==0.11.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==2.0.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - orjson==3.10.7
      - pandas==2.2.2
      - pillow==10.4.0
      - protobuf==5.27.2
      - psutil==6.0.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pycm==4.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.3.3
      - regex==2024.9.11
      - rich==13.9.3
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - sentry-sdk==2.10.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - tokenizers==0.21.1
      - torch==2.3.1
      - torchmetrics==1.4.0.post0
      - torchvision==0.18.1
      - tqdm==4.66.4
      - transformers==4.50.3
      - tzdata==2024.1
      - uv==0.6.11
      - wandb==0.17.5
      - xlsxwriter==3.2.0
      - xxhash==3.4.1
      - yarl==1.9.4
