project_name: 'fairread'
run_mode: cross_validation
model: erm
target: 'Pleural Effusion'
num_gpus: 1
additional_tags: ['erm']

num_classes: 1
learning_rate: 0.0001
batch_size: 64
cv_fold_total: 5
# placeholder for cross validation fold index
cv_fold_idx: 0

data_root: '/path/to/data/'
patient_labels_path: '${data_root}/train.csv'
patient_info_path: '${data_root}/CHEXPERT DEMO.xlsx'
image_root: '${data_root}/'
sensitive_attributes: ['PRIMARY_RACE', 'GENDER', 'AGE_AT_CXR']
use_attrs: {
    'PRIMARY_RACE': ['White', 'Non-White'],
    'GENDER': ['Female', 'Male'],
    'AGE_AT_CXR': ['<60', '>=60'],
}

model_save_root: checkpoints/erm_${target}_cross_validation/
data_cache_path: data_cache/${target}_cv.pkl

max_epochs: 10

use_group_specific_threshold: True
print_calibration: False
plot_subgroup_performance: True

test_refit_threshold: False